#!/usr/bin/env bash

# Compiler-free audit for the typed, bounded POSIX file-stream contract.
set -euo pipefail

script_dir="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
repo_root="$(CDPATH= cd -- "$script_dir/.." && pwd)"
stream="$repo_root/src/runtime/stream_posix.elisa"
ir="$repo_root/src/ir/ir.elisa"
tests="$repo_root/test/ir/elisascript_ir_test.elisa"
docs="$repo_root/docs/ir.md"
plan="$repo_root/IMPLEMENTATION_PLAN.md"

for required_file in "$stream" "$ir" "$tests" "$docs" "$plan"; do
    if [[ ! -f "$required_file" ]]; then
        printf 'streaming file audit: missing %s\n' "$required_file" >&2
        exit 1
    fi
done

rg -q 'include "\.\./runtime/stream_posix\.elisa"' "$ir"
rg -q '^error FileStreamError:' "$stream"
rg -q '^    OpenFailed\(path: cstr\)$' "$stream"
rg -q '^    ReadFailed\(path: cstr\)$' "$stream"
rg -q '^    WriteFailed\(path: cstr\)$' "$stream"
rg -q '^    FlushFailed\(path: cstr\)$' "$stream"
rg -q '^    InvalidEncoding\(path: cstr\)$' "$stream"
rg -q '^    InvalidUtf8\(path: cstr\)$' "$stream"
rg -q '^    SyncFailed\(path: cstr\)$' "$stream"
rg -q '^    CloseFailed\(path: cstr\)$' "$stream"
rg -q '^    SeekFailed\(path: cstr\)$' "$stream"
rg -q '^    PublishFailed\(path: cstr\)$' "$stream"
rg -q '^    PathCollision\(path: cstr\)$' "$stream"
rg -q '^    DirectorySyncFailed\(path: cstr\)$' "$stream"
rg -q '^    CleanupStateInvalid\(path: cstr\)$' "$stream"
rg -q '^    Closed\(path: cstr\)$' "$stream"
rg -q '^    WrongMode\(path: cstr\)$' "$stream"
rg -q '^    LimitExceeded\(path: cstr\)$' "$stream"
rg -q '^    PathTooLong\(path: cstr\)$' "$stream"
rg -q '^    LineTooLong\(path: cstr\)$' "$stream"
rg -q '^    InvalidLineMode\(path: cstr\)$' "$stream"
rg -q 'const FILE_STREAM_DEFAULT_MAX_BYTES: usize = ES_RUNTIME_DEFAULT_MAX_MEMORY_BYTES' "$stream"
rg -q '^        const enum FileStreamMode of u8:' "$stream"
rg -q '^        const enum FileStreamState of u8:' "$stream"
rg -q '^        struct FileStreamRead:' "$stream"
rg -q '^        struct FileStreamWrite:' "$stream"
rg -q '^        struct FileStream:' "$stream"
rg -q 'def file_stream_open\(' "$stream"
rg -q 'encoding: FileStreamEncoding = FileStreamEncoding.Auto' "$stream"
rg -q 'resolved_encoding: FileStreamEncoding' "$stream"
rg -q 'const FILE_STREAM_MAX_PATH_BYTES: usize = 4096' "$stream"
rg -q 'def file_stream_path_terminated\(' "$stream"
rg -q 'def file_stream_path_equal\(' "$stream"
rg -q 'return false if bytes\[0\] == 0' "$stream"
rg -q 'PathTooLong\(path\) if not file_stream_path_terminated\(path\)' "$stream"
rg -q '^        const enum FileStreamLineMode of u8:' "$stream"
rg -q '^        const enum FileStreamEncoding of u8:' "$stream"
rg -q '^        const enum FileStreamSeekOrigin of u8:' "$stream"
rg -q '^        const enum FileStreamRecordState of u8:' "$stream"
rg -q '^        const enum FileStreamByteState of u8:' "$stream"
rg -q '^        const enum FileStreamWriteState of u8:' "$stream"
rg -q 'def file_stream_write_transition\(' "$stream"
rg -q 'def file_stream_read_byte\(' "$stream"
rg -q 'read_count: usize = fread' "$stream"
rg -q 'read_count > remaining or ferror\(handle\) != 0' "$stream"
rg -q 'amount > 1 or ferror\(handle\) != 0' "$stream"
rg -q 'EncodingError' "$stream"
rg -q 'def file_stream_mode_is_text\(' "$stream"
rg -q 'def file_stream_encoding_valid\(' "$stream"
rg -q 'def file_stream_utf8_feed\(' "$stream"
rg -q 'def file_stream_utf8_validate\(' "$stream"
rg -q 'EsEncoding::Utf8Cursor' "$stream"
rg -q 'def file_stream_record_next\(' "$stream"
rg -U -q 'return FileStreamByteState\.Limit if stream\.bytes_read >= stream\.byte_budget\n            handle: mutable heap void& = stream\.handle\n            amount: usize = fread' "$stream"
rg -q 'byte != 13' "$stream"
rg -q 'pending_valid' "$stream"
rg -q 'lookahead' "$stream"
rg -q 'def file_stream_read_chunk\(' "$stream"
rg -U -q 'if stream\.pending_valid:\n                buffer\[0\] <- stream\.pending_byte\n                stream\.pending_valid <- false' "$stream"
rg -q 'remaining: usize = capacity - count' "$stream"
rg -q 'cursor: mutable u8& = buffer \+ count' "$stream"
rg -q 'def file_stream_write_chunk\(' "$stream"
rg -U -q 'offset: mutable usize = 0\n            while offset < capacity:' "$stream"
rg -q 'cursor: mutable u8& = buffer \+ offset' "$stream"
rg -q 'write_count: usize = fwrite' "$stream"
rg -q 'amount == 0 or amount > capacity - offset' "$stream"
rg -q 'state == FileStreamWriteState\.Error' "$stream"
rg -q 'ferror\(handle\) != 0' "$stream"
rg -q 'stream\.bytes_written <- stream\.bytes_written \+ offset' "$stream"
rg -q 'def file_stream_sync\(' "$stream"
rg -q 'fflush\(handle\)' "$stream"
rg -q 'def file_stream_publish_staged\(' "$stream"
rg -q 'PathCollision\(staging_path\) if file_stream_path_equal\(staging_path, destination_path\)' "$stream"
rg -q 'elisascript_posix_rename\(staging_path\.cast\[u8&\], destination_path\.cast\[u8&\]\)' "$stream"
rg -q 'elisascript_posix_opendir\(directory_path\)' "$stream"
rg -q 'elisascript_posix_closedir\(opened\)' "$stream"
rg -q 'stream\.mode != FileStreamMode\.WriteText and stream\.mode != FileStreamMode\.WriteBinary' "$stream"
rg -q 'def file_stream_tell\(' "$stream"
rg -q 'def file_stream_seek\(' "$stream"
rg -q 'stream\.pending_valid and origin == FileStreamSeekOrigin\.Current' "$stream"
rg -q 'fseek\(handle, -1, FILEIO_SEEK_CUR\)' "$stream"
rg -q 'stream\.pending_byte <- 0' "$stream"
rg -q 'def file_stream_read_line_mode\(' "$stream"
rg -q 'FileStreamLineMode\.Universal' "$stream"
rg -q 'FileStreamLineMode\.Retain' "$stream"
rg -q 'def file_stream_read_line\(' "$stream"
rg -q 'def file_stream_close\(' "$stream"
rg -q 'const enum FileStreamCleanupState of u8:' "$stream"
rg -q 'struct FileStreamCleanupGuard:' "$stream"
rg -q 'def file_stream_cleanup_begin\(' "$stream"
rg -q 'def file_stream_cleanup_commit\(' "$stream"
rg -q 'def file_stream_cleanup_abort\(' "$stream"
rg -q 'guard\.state != FileStreamCleanupState\.Armed' "$stream"
rg -q 'stream\.state == FileStreamState\.Closed and stream\.handle != null' "$stream"
rg -q 'stream\.state == FileStreamState\.Closed$' "$stream"
rg -q 'stream\.handle == null' "$stream"
rg -q 'remaining > stream\.byte_budget - stream\.bytes_read' "$stream"
rg -q 'capacity > stream\.byte_budget - stream\.bytes_written' "$stream"
! rg -q 'machine over fread\(' "$stream"
rg -q 'Read, FileStreamRecordState\.Limit:' "$stream"
rg -q 'Read, FileStreamRecordState\.LineTooLong:' "$stream"
rg -q 'Read, FileStreamRecordState\.EncodingError:' "$stream"
rg -q 'Read, FileStreamRecordState\.Error:' "$stream"
rg -q 'stream\.state <- FileStreamState\.Closed' "$stream"
rg -q 'typed_file_stream_contract_is_bounded_and_stateful' "$tests"
rg -q 'typed_file_stream_write_contract_retries_short_progress' "$tests"
rg -q 'file_stream_write_transition\(0, 8, 3, 8\)' "$tests"
rg -q 'typed_file_stream_newline_modes_are_explicit' "$tests"
rg -q 'FileStreamLineMode\.Universal' "$tests"
rg -q 'typed_file_stream_staged_publication_contract_is_explicit' "$tests"
rg -q 'typed_file_stream_encoding_policy_is_explicit' "$tests"
rg -q 'FileStreamEncoding\.Utf8' "$tests"
rg -q 'typed_file_stream_utf8_boundary_state_is_explicit' "$tests"
rg -q 'utf8_remaining: 2u8' "$tests"
rg -q 'utf8_lower: 160u8' "$tests"
rg -q 'utf8_remaining: 3u8' "$tests"
rg -q 'utf8_lower: 144u8' "$tests"
rg -q 'typed_file_stream_close_rejects_open_without_handle' "$tests"
rg -q 'FileStreamCleanupGuard' "$tests"
rg -q 'file_stream_cleanup_transition' "$tests"
rg -q 'file_stream_cleanup_transition\(FileStreamCleanupState\.Closed, FileStreamCleanupEvent\.Commit\)' "$tests"
rg -q 'file_stream_cleanup_transition\(FileStreamCleanupState\.Closed, FileStreamCleanupEvent\.Abort\)' "$tests"
rg -q 'file_stream_cleanup_transition\(FileStreamCleanupState\.Aborted, FileStreamCleanupEvent\.Commit\)' "$tests"
rg -q 'file_stream_cleanup_transition\(FileStreamCleanupState\.Aborted, FileStreamCleanupEvent\.Abort\)' "$tests"
rg -q 'typed streaming file handles|FileStream|file_stream_read_line' "$docs"
rg -q 'Q06:.*FileStream|Q06:.*typed streaming' "$plan"

printf 'streaming file audit: typed modes, bounded chunk/line operations, and close-state contract present\n'
