#!/usr/bin/env bash

# Compiler-free audit for the shared serialized-slice admission invariant.
set -euo pipefail

script_dir="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
repo_root="$(CDPATH= cd -- "$script_dir/.." && pwd)"
runtime_model="$repo_root/src/ir/runtime_model.elisa"
bytecode="$repo_root/src/bytecode/bytecode.elisa"
artifact_cache="$repo_root/src/ir/artifact_cache.elisa"
verifier="$repo_root/src/ir/ir_verify.elisa"
tests="$repo_root/test/ir/elisascript_ir_test.elisa"
plan="$repo_root/IMPLEMENTATION_PLAN.md"

for required_file in "$runtime_model" "$bytecode" "$artifact_cache" "$verifier" "$tests" "$plan"; do
    if [[ ! -f "$required_file" ]]; then
        printf 'serialization bounds audit: missing %s\n' "$required_file" >&2
        exit 1
    fi
done

rg -q 'def runtime_bounded_slice_end' "$runtime_model"
rg -q 'return false if length > bound - start' "$runtime_model"
rg -q 'runtime_bounded_slice_end\(offset, length_host, bytes.count, end\)' "$bytecode"
rg -q 'runtime_bounded_slice_end\(offset, length_host, bytes.count, end\)' "$repo_root/src/testing/differential.elisa"
rg -q 'length\.usize\(\)\.u64\(\) != length' "$bytecode"
rg -q 'length\.usize\(\)\.u64\(\) != length' "$repo_root/src/testing/differential.elisa"
! rg -q 'offset \+ 2 > bytes.count|offset \+ 4 > bytes.count|length > \(bytes.count - offset\)' "$repo_root/src/testing/differential.elisa"
rg -q 'bytecode_artifact_bytes_valid' "$bytecode"
rg -q 'def bytecode_artifact_envelope_status' "$bytecode"
rg -q 'def bytecode_artifact_requires_migration' "$bytecode"
rg -q 'def bytecode_artifact_byte_range_has_nul' "$bytecode"
rg -q 'def migrate_bytecode_artifact' "$bytecode"
rg -q 'def classify_bytecode_artifact_cache' "$artifact_cache"
rg -q 'def artifact_cache_lifecycle_transition' "$artifact_cache"
rg -q 'bytecode_block_layout_valid' "$bytecode"
rg -q 'saturat|saturated|range' "$verifier"
rg -q 'serialized_slice_bounds_use_subtraction_before_end_addition' "$tests"
rg -q 'def canonical_bytes_sha256' "$repo_root/src/ir/serialize.elisa"
rg -q 'def canonical_module_digest' "$repo_root/src/ir/serialize.elisa"
rg -q 'def canonical_digest_word' "$repo_root/src/ir/serialize.elisa"
rg -q 'def canonical_module_digest_word' "$repo_root/src/ir/serialize.elisa"
rg -q 'CANONICAL_SHA256_MAX_INPUT_BYTES' "$repo_root/src/ir/serialize.elisa"
rg -q 'canonical_sha256_matches_known_vectors' "$tests"
rg -q 'module_digest_0' "$bytecode"
rg -q 'bytes\[4\] != 2' "$bytecode"
rg -q 'legacy_version' "$repo_root/test/ir/elisascript_bytecode_test.elisa"
rg -q 'bytecode_artifact_requires_migration' "$repo_root/test/ir/elisascript_bytecode_test.elisa"
rg -q 'malformed_revision' "$repo_root/test/ir/elisascript_bytecode_test.elisa"
rg -q 'migrate_bytecode_artifact' "$repo_root/test/ir/elisascript_bytecode_test.elisa"
rg -q 'digest_0' "$repo_root/src/ir/artifact.elisa"
rg -q 'format_version: u8 = 2' "$repo_root/src/ir/artifact.elisa"
rg -q 'def canonical_module_artifact_bytes' "$repo_root/src/ir/artifact.elisa"
rg -q 'def module_artifact_bytes_valid' "$repo_root/src/ir/artifact.elisa"
rg -q 'def module_artifact_envelope_status' "$repo_root/src/ir/artifact.elisa"
rg -q 'def module_artifact_requires_migration' "$repo_root/src/ir/artifact.elisa"
rg -q 'def module_artifact_byte_range_has_nul' "$repo_root/src/ir/artifact.elisa"
rg -q 'def migrate_module_artifact' "$repo_root/src/ir/artifact.elisa"
rg -q 'def classify_module_artifact_cache' "$artifact_cache"
rg -q 'def load_module_artifact_file' "$artifact_cache"
rg -q 'def load_bytecode_artifact_file' "$artifact_cache"
rg -q 'def publish_module_artifact_file' "$artifact_cache"
rg -q 'def publish_bytecode_artifact_file' "$artifact_cache"
rg -q 'def artifact_cache_write_staging' "$artifact_cache"
rg -q 'catch artifact_cache_write_staging' "$artifact_cache"
! rg -q 'try artifact_cache_write_staging' "$artifact_cache"
rg -q 'catch file_stream_sync' "$artifact_cache"
rg -q 'ArtifactCacheIoError\.PublishFailed' "$artifact_cache"
rg -q 'elisascript_posix_rename' "$artifact_cache"
rg -q 'def artifact_cache_stage' "$artifact_cache"
rg -q 'runtime_bounded_slice_end\(offset, length\.usize\(\), bytes.count, end\)' "$repo_root/src/ir/artifact.elisa"
rg -q 'legacy_artifact_bytes' "$tests"
rg -q 'malformed_artifact_digest' "$tests"
rg -q 'module_artifact_requires_migration' "$tests"
rg -q 'malformed_artifact_text' "$tests"
rg -q 'migrate_module_artifact' "$tests"
rg -q 'ArtifactCacheLifecycle.Staged' "$tests"
rg -q 'ArtifactCacheLoad' "$tests"
rg -q 'ArtifactCacheEvent.Commit' "$tests"
rg -q 'struct ArtifactCacheWriterLease' "$artifact_cache"
rg -q 'def artifact_cache_writer_acquire' "$artifact_cache"
rg -q 'def artifact_cache_writer_publish' "$artifact_cache"
rg -q 'def artifact_cache_writer_abort' "$artifact_cache"
rg -q 'artifact_cache_writer_acquire\(lease, 41\)' "$tests"
rg -q 'artifact_cache_writer_acquire\(aborted, 0\)' "$tests"
rg -q 'artifact_cache_writer_acquire\(aborted, 8\)' "$tests"
rg -q 'artifact_cache_writer_publish\(aborted, 8\)' "$tests"
rg -q 'module_digest_0' "$repo_root/src/testing/differential.elisa"
rg -q 'def make_differential_artifact_manifest_for_module' "$repo_root/src/testing/differential.elisa"
rg -q 'def differential_artifact_manifest_requires_migration' "$repo_root/src/testing/differential.elisa"
rg -q 'manifest.format_version != 4' "$repo_root/src/testing/differential.elisa"
rg -q 'bytes\[4\] != 4' "$repo_root/src/testing/differential.elisa" || rg -q 'bytes\[4\] != 1 and bytes\[4\] != 2 and bytes\[4\] != 3 and bytes\[4\] != 4' "$repo_root/src/testing/differential.elisa"
rg -q 'digest_manifest' "$repo_root/test/differential/elisascript_differential_test.elisa"
rg -q 'malformed_manifest_length' "$repo_root/test/differential/elisascript_differential_test.elisa"
rg -q 'differential_artifact_manifest_requires_migration' "$repo_root/test/differential/elisascript_differential_test.elisa"
rg -q 'Q02a:' "$plan"
printf 'serialization bounds audit: shared slice admission, bytecode reader, verifier, and fixture present\n'
