#!/usr/bin/env bash

# Compiler-free audit for the typed, shell-free process command model.
set -euo pipefail

script_dir="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
repo_root="$(CDPATH= cd -- "$script_dir/.." && pwd)"
model="$repo_root/src/runtime/process_model.elisa"
ir="$repo_root/src/ir/ir.elisa"
fixture="$repo_root/test/ir/elisascript_ir_test.elisa"
differential_source="$repo_root/src/testing/differential.elisa"
differential_fixture="$repo_root/test/differential/elisascript_differential_test.elisa"
differential_docs="$repo_root/docs/differential-testing.md"
docs="$repo_root/docs/ir.md"
plan="$repo_root/IMPLEMENTATION_PLAN.md"

for required_file in "$model" "$ir" "$fixture" "$differential_source" "$differential_fixture" "$differential_docs" "$docs" "$plan"; do
    if [[ ! -f "$required_file" ]]; then
        printf 'process command audit: missing %s\n' "$required_file" >&2
        exit 1
    fi
done

rg -q '^module EsProcess:' "$model"
rg -q 'include "\.\./runtime/process_model\.elisa"' "$ir"
rg -q '^        const enum ProcessStdioMode of u8:' "$model"
rg -q '^        const enum ProcessEnvironmentMode of u8:' "$model"
rg -q '^        const enum ProcessFailureMode of u8:' "$model"
rg -q '^        const enum ProcessResultKind of u8:' "$model"
rg -q '^        struct ProcessResult:' "$model"
rg -q '^        struct ProcessCommand:' "$model"
rg -q '^        error ProcessCommandError:' "$model"
rg -q '^        error ProcessResultError:' "$model"
rg -q '^            executable: sview$' "$model"
rg -q '^            arguments: darray\[sview\] = \[\]$' "$model"
rg -q '^            working_directory: sview = ""$' "$model"
rg -q '^            environment: darray\[sview\] = \[\]$' "$model"
rg -q '^            stdin_path: sview = ""$' "$model"
rg -q '^            stdout_path: sview = ""$' "$model"
rg -q '^            stderr_path: sview = ""$' "$model"
rg -q '^            timeout_micros: u64 = 0$' "$model"
rg -q 'def validate_process_command\(' "$model"
rg -q 'def resolve_process_environment\(' "$model"
rg -q 'def validate_process_environment_vector\(' "$model"
rg -q 'def validate_process_result\(' "$model"
rg -q 'error\[ProcessCommandError\]' "$model"
rg -q 'error\[ProcessResultError\]' "$model"
rg -q 'process_command_text_has_nul' "$model"
rg -q 'ProcessCommandError\.ArgumentCountExceeded' "$model"
rg -q 'raise ProcessCommandError\.EnvironmentVectorMalformed if command\.environment\.count % 2 != 0' "$model"
rg -q 'EnvironmentCountExceeded' "$model"
rg -q 'entries\.count / 2 > PROCESS_COMMAND_MAX_ARGUMENTS' "$model"
rg -q 'ProcessCommandError\.DuplicateEnvironmentName' "$model"
rg -q 'ProcessCommandError\.InvalidStdioMode' "$model"
rg -q 'ProcessCommandError\.InvalidStdioPath' "$model"
rg -q 'ProcessCommandError\.StdioPathEmbeddedNul' "$model"
rg -q 'ProcessResultError\.InvalidSignal' "$model"
rg -q 'result\.exit_status < 0' "$model"
rg -q 'PROCESS_MAX_SIGNAL' "$model"
rg -q 'ProcessResultError\.AggregateTextLimitExceeded' "$model"
rg -q 'ProcessPipelineError\.PipelineAccountingInvalid' "$model"
rg -q 'pipeline\.state == ProcessPipelineState\.Cancelled' "$model"
rg -q 'state: ProcessPipelineState\.Cancelled, completed_stages: 2' "$fixture"
rg -q 'process_command_text_add_fits' "$model"
rg -q 'process_command_text_add_fits\(total, command\.working_directory\)' "$model"
rg -q 'process_command_text_length_valid' "$model"
rg -q 'process_command_stdio_path_valid' "$model"
rg -q 'sview_len\(value\) < PROCESS_COMMAND_MAX_TEXT_BYTES' "$model"
rg -q 'sview_contains_byte\(name, 61\)' "$model"
rg -q 'using EsProcess' "$fixture"
rg -q 'typed_process_command_contract_is_shell_free_and_bounded' "$fixture"
rg -q 'ProcessCommandError\.EmbeddedNul' "$fixture"
rg -q 'ProcessCommandError\.DuplicateEnvironmentName' "$fixture"
rg -q 'working_directory_command' "$fixture"
rg -q 'resolve_process_environment' "$fixture"
rg -q 'ProcessEnvironmentMode\.Replace' "$fixture"
rg -q 'ProcessEnvironmentMode\.Clear' "$fixture"
rg -q 'ProcessCommandError\.InvalidStdioPath' "$fixture"
rg -q 'ProcessCommandError\.StdioPathEmbeddedNul' "$fixture"
rg -q 'ProcessResultKind\.Signaled' "$fixture"
rg -q 'ProcessResultError\.InvalidSignal' "$fixture"
rg -q 'ProcessResultError\.EmbeddedNul' "$fixture"
rg -q 'PROCESS_COMMAND_MAX_ARGUMENTS' "$docs"
rg -q 'validate_process_command' "$docs"
rg -q 'shell-free' "$docs"
rg -q 'stdin_path: sview = ""' "$model"
rg -q 'A `File` mode must carry its corresponding' "$docs"
rg -q 'EsProcess::ProcessResult' "$docs"
rg -q 'ProcessResultError' "$docs"
rg -q 'P10 typed-command follow-up' "$plan"
rg -q 'using EsProcess' "$differential_source"
rg -q 'def differential_process_command_valid\(' "$differential_source"
rg -q 'validate_process_command\(command\)' "$differential_source"
rg -q 'not differential_process_command_valid\(invocation\)' "$differential_source"
rg -q 'def differential_process_result_from_status\(' "$differential_source"
rg -q 'validate_process_result\(result\)' "$differential_source"
rg -q 'process_result: ProcessResult' "$differential_source"
rg -q 'differential_process_execution_reuses_typed_command_environment_contract' "$differential_fixture"
rg -q 'EsProcess::ProcessCommand' "$differential_docs"

printf 'process command audit: typed shell-free command values, bounded vectors, and error[...] validation are present\n'
